version: "3.11"
services:
    errors:
        restart: always
        build: .
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=scrape_with_errors.py
          - APP_NO_OF_THREADS=1
        deploy:
          resources:
            limits:
              cpus: "1"
              memory: 3G
        volumes:
          - ./logs/:/www/logs/
          
    sitemap:
        restart: always
        build: .
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=add-new-urls.py
          - APP_NO_OF_THREADS=1
        deploy:
          resources:
            limits:
              cpus: "1"
              memory: 3G
        volumes:
          - ./logs/:/www/logs/
    
    alldb:
        restart: always
        build: .
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=rescrape_all_from_db.py
          - APP_NO_OF_THREADS=5
        deploy:
          resources:
            limits:
              cpus: "4"
              memory: 10G
        volumes:
          - ./logs/:/www/logs/
          - ./file/:/www/file/
        
    api:
        restart: always
        build: .
        ports:
          - 3060:3060
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=api.py
          - APP_NO_OF_THREADS=1
        deploy:
          resources:
            limits:
              cpus: "1"
              memory: 256M
        volumes:
          - ./logs/:/www/logs/