version: "3.11"
services:
    errors:
        # Fix: use init or will be many chrome (defunct) which overflow process table and server freeze
        # https://docs.docker.com/engine/reference/run/#specify-an-init-process
        init: true
        restart: always
        build: .
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=scrape_with_errors.py
          - APP_NO_OF_THREADS=1
        deploy:
          resources:
            limits:
              cpus: "1"
              memory: 3G
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "2"

        volumes:
          - ./logs/:/www/logs/
          
    sitemap:
        # Fix: use init or will be many chrome (defunct) which overflow process table and server freeze
        # https://docs.docker.com/engine/reference/run/#specify-an-init-process
        init: true
        restart: always
        build: .
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=add-new-urls.py
          - APP_NO_OF_THREADS=1
        deploy:
          resources:
            limits:
              cpus: "1"
              memory: 3G
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "2"
        volumes:
          - ./logs/:/www/logs/
    alldb:
        # Fix: use init or will be many chrome (defunct) which overflow process table and server freeze
        # https://docs.docker.com/engine/reference/run/#specify-an-init-process
        init: true
        restart: always
        build: .
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=rescrape_all_from_db.py
          - APP_NO_OF_THREADS=3
        deploy:
          resources:
            limits:
              cpus: "4"
              memory: 10G
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "2"
        volumes:
          - ./logs/:/www/logs/
        
    api:
        # Fix: use init or will be many chrome (defunct) which overflow process table and server freeze
        # https://docs.docker.com/engine/reference/run/#specify-an-init-process
        init: true
        restart: always
        build: .
        ports:
          - 3060:3060
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=api.py
          - APP_NO_OF_THREADS=1
        deploy:
          resources:
            limits:
              cpus: "1"
              memory: 256M
        volumes:
          - ./logs/:/www/logs/