version: "3.11"
services:
    dev:
        # Fix: use init or will be many chrome (defunct) which overflow process table and server freeze
        # https://docs.docker.com/engine/reference/run/#specify-an-init-process
        init: true
        build:
          dockerfile: Dockerfile-dev
        command: tail -f /dev/null
        environment:
          - USE_MARIA_DB=1
          - GET_SOURCE_CODE=1
          - DB_HOST=${DB_HOST}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_NAME=${DB_NAME}
          - APP_TARGET=api.py
          - APP_NO_OF_THREADS=1
        volumes:
          - ./:/www