<?php
namespace DataExport\Formatters;

use function MongoDB\Driver\Monitoring\addSubscriber;

class WebFormatter
{
    public static function fromString( ?string $text ): ?array
    {
        if ( !$text ) return null;

        $phones = explode( "\n", $text );
        $phones = array_map( "trim", $phones );
        $phones = array_map( [ __CLASS__ , "format" ], $phones );
        $phones = array_filter( $phones, "strlen" );

        return $phones;
    }

    private static function onlyValidWeb( string $web ): string
    {
        return filter_var( $web, FILTER_VALIDATE_URL) ? $web : "";
    }

    private static function isSpecialDomain( string $domain ): bool
    {
        $specDomains = [
            "yellowpages.com",
            "manta.com"
        ];

        foreach( $specDomains as $specDomain )
        {
            if ( stripos( $domain, $specDomain ) !== false )
            {
                return true;
            }
        }

        return false;
    }

    public static function format( string $web ): string
    {
        # filter_var($url, FILTER_VALIDATE_URL)
        $web = !preg_match( "#^https?\://#si", $web ) ? "https://".$web : $web;
        $web = preg_replace( "#http\://#si", "https://", $web );

        $purl = parse_url( $web );

        $domain = $purl["host"] ?? "";
        if ( !$domain ) return static::onlyValidWeb( $web );

        if ( static::isSpecialDomain( $domain ) ) return "";

        $root = static::getRootDomain( $domain );
        if ( $root === false ) return static::onlyValidWeb( $web );

        if ( $root === $domain )
        {
            $domain = "www.".$domain;
        }

        return static::onlyValidWeb( "https://"
            .$domain
            .( isset( $purl["port"] ) ? ":".$purl["port"] : "" )
            .( $purl["path"] ?? "" )
            .( isset( $purl["query"] ) ? "?".$purl["query"] : "" )
        );
    }

    private static function getRootDomain( $domain )
    {
        if ( empty( $domain ) )
        {
            return false;
        }

        $endings = static::getDomainEndings();

        foreach ( $endings as $ending )
        {
            if ( preg_match( "#([a-z\-0-9]{2,63})".preg_quote( $ending, "#" )."$#si", $domain, $m ) )
            {
                return $m[1].$ending;
            }
        }

        return false;
    }

    public function getDomainEndings(): array
    {
        # order by length(name),casestrcmp(name)
        return [
            0 => '.international',
            1 => '.construction',
            2 => '.accountants',
            3 => '.contractors',
            4 => '.engineering',
            5 => '.enterprises',
            6 => '.investments',
            7 => '.photography',
            8 => '.productions',
            9 => '.accountant',
            10 => '.apartments',
            11 => '.associates',
            12 => '.consulting',
            13 => '.foundation',
            14 => '.healthcare',
            15 => '.immobilien',
            16 => '.industries',
            17 => '.management',
            18 => '.properties',
            19 => '.realestate',
            20 => '.republican',
            21 => '.restaurant',
            22 => '.technology',
            23 => '.university',
            24 => '.vlaanderen',
            25 => '.community',
            26 => '.directory',
            27 => '.education',
            28 => '.equipment',
            29 => '.financial',
            30 => '.furniture',
            31 => '.institute',
            32 => '.marketing',
            33 => '.melbourne',
            34 => '.school.nz',
            35 => '.solutions',
            36 => '.vacations',
            37 => '.attorney',
            38 => '.bargains',
            39 => '.boutique',
            40 => '.brussels',
            41 => '.builders',
            42 => '.business',
            43 => '.capetown',
            44 => '.catering',
            45 => '.cleaning',
            46 => '.clothing',
            47 => '.computer',
            48 => '.delivery',
            49 => '.democrat',
            50 => '.diamonds',
            51 => '.discount',
            52 => '.download',
            53 => '.engineer',
            54 => '.exchange',
            55 => '.football',
            56 => '.graphics',
            57 => '.holdings',
            58 => '.hospital',
            59 => '.lighting',
            60 => '.maori.nz',
            61 => '.memorial',
            62 => '.mortgage',
            63 => '.partners',
            64 => '.pictures',
            65 => '.plumbing',
            66 => '.services',
            67 => '.shopping',
            68 => '.software',
            69 => '.supplies',
            70 => '.training',
            71 => '.ventures',
            72 => '.yokohama',
            73 => '.academy',
            74 => '.auction',
            75 => '.capital',
            76 => '.careers',
            77 => '.charity',
            78 => '.college',
            79 => '.cologne',
            80 => '.company',
            81 => '.compare',
            82 => '.contact',
            83 => '.cooking',
            84 => '.country',
            85 => '.coupons',
            86 => '.courses',
            87 => '.cricket',
            88 => '.cruises',
            89 => '.dentist',
            90 => '.digital',
            91 => '.domains',
            92 => '.exposed',
            93 => '.express',
            94 => '.fashion',
            95 => '.finance',
            96 => '.fishing',
            97 => '.fitness',
            98 => '.flights',
            99 => '.florist',
            100 => '.forsale',
            101 => '.gallery',
            102 => '.geek.nz',
            103 => '.hamburg',
            104 => '.holiday',
            105 => '.jewelry',
            106 => '.jpn.com',
            107 => '.kitchen',
            108 => '.kiwi.nz',
            109 => '.limited',
            110 => '.network',
            111 => '.okinawa',
            112 => '.organic',
            113 => '.recipes',
            114 => '.rentals',
            115 => '.reviews',
            116 => '.science',
            117 => '.shiksha',
            118 => '.singles',
            119 => '.support',
            120 => '.surgery',
            121 => '.systems',
            122 => '.theater',
            123 => '.trading',
            124 => '.website',
            125 => '.wedding',
            126 => '.ae.org',
            127 => '.africa',
            128 => '.agency',
            129 => '.bayern',
            130 => '.beauty',
            131 => '.berlin',
            132 => '.boston',
            133 => '.br.com',
            134 => '.camera',
            135 => '.career',
            136 => '.casino',
            137 => '.center',
            138 => '.church',
            139 => '.claims',
            140 => '.clinic',
            141 => '.cn.com',
            142 => '.coffee',
            143 => '.com.ar',
            144 => '.com.au',
            145 => '.com.sb',
            146 => '.com.sg',
            147 => '.condos',
            148 => '.credit',
            149 => '.dating',
            150 => '.degree',
            151 => '.dental',
            152 => '.design',
            153 => '.direct',
            154 => '.doctor',
            155 => '.durban',
            156 => '.energy',
            157 => '.estate',
            158 => '.eu.com',
            159 => '.events',
            160 => '.expert',
            161 => '.family',
            162 => '.futbol',
            163 => '.garden',
            164 => '.gen.nz',
            165 => '.global',
            166 => '.gratis',
            167 => '.health',
            168 => '.hockey',
            169 => '.insure',
            170 => '.joburg',
            171 => '.kaufen',
            172 => '.lawyer',
            173 => '.london',
            174 => '.maison',
            175 => '.market',
            176 => '.nagoya',
            177 => '.net.au',
            178 => '.net.nz',
            179 => '.online',
            180 => '.org.au',
            181 => '.org.nz',
            182 => '.org.uk',
            183 => '.photos',
            184 => '.quebec',
            185 => '.racing',
            186 => '.reisen',
            187 => '.repair',
            188 => '.report',
            189 => '.review',
            190 => '.ru.com',
            191 => '.ryukyu',
            192 => '.sa.com',
            193 => '.school',
            194 => '.schule',
            195 => '.select',
            196 => '.soccer',
            197 => '.social',
            198 => '.stream',
            199 => '.studio',
            200 => '.supply',
            201 => '.sydney',
            202 => '.taipei',
            203 => '.tattoo',
            204 => '.tennis',
            205 => '.tienda',
            206 => '.uk.com',
            207 => '.us.com',
            208 => '.viajes',
            209 => '.villas',
            210 => '.vision',
            211 => '.voyage',
            212 => '.webcam',
            213 => '.za.com',
            214 => '.орг',
            215 => '.ac.nz',
            216 => '.actor',
            217 => '.adult',
            218 => '.archi',
            219 => '.bingo',
            220 => '.black',
            221 => '.boats',
            222 => '.build',
            223 => '.cards',
            224 => '.cheap',
            225 => '.click',
            226 => '.cloud',
            227 => '.co.nz',
            228 => '.co.uk',
            229 => '.co.za',
            230 => '.coach',
            231 => '.codes',
            232 => '.dance',
            233 => '.deals',
            234 => '.earth',
            235 => '.email',
            236 => '.faith',
            237 => '.games',
            238 => '.gifts',
            239 => '.gives',
            240 => '.glass',
            241 => '.green',
            242 => '.gripe',
            243 => '.group',
            244 => '.guide',
            245 => '.homes',
            246 => '.horse',
            247 => '.house',
            248 => '.id.au',
            249 => '.jetzt',
            250 => '.koeln',
            251 => '.kyoto',
            252 => '.lease',
            253 => '.legal',
            254 => '.loans',
            255 => '.me.uk',
            256 => '.media',
            257 => '.miami',
            258 => '.money',
            259 => '.ninja',
            260 => '.osaka',
            261 => '.paris',
            262 => '.parts',
            263 => '.party',
            264 => '.photo',
            265 => '.pizza',
            266 => '.place',
            267 => '.poker',
            268 => '.press',
            269 => '.promo',
            270 => '.quest',
            271 => '.rehab',
            272 => '.reise',
            273 => '.rocks',
            274 => '.rodeo',
            275 => '.salon',
            276 => '.shoes',
            277 => '.solar',
            278 => '.space',
            279 => '.store',
            280 => '.study',
            281 => '.style',
            282 => '.tires',
            283 => '.today',
            284 => '.tokyo',
            285 => '.tools',
            286 => '.tours',
            287 => '.trade',
            288 => '.vegas',
            289 => '.video',
            290 => '.vodka',
            291 => '.wales',
            292 => '.watch',
            293 => '.works',
            294 => '.world',
            295 => '.asia',
            296 => '.band',
            297 => '.beer',
            298 => '.best',
            299 => '.bike',
            300 => '.blog',
            301 => '.blue',
            302 => '.buzz',
            303 => '.cafe',
            304 => '.camp',
            305 => '.care',
            306 => '.casa',
            307 => '.cash',
            308 => '.chat',
            309 => '.city',
            310 => '.club',
            311 => '.cool',
            312 => '.cyou',
            313 => '.date',
            314 => '.fail',
            315 => '.fans',
            316 => '.farm',
            317 => '.fish',
            318 => '.fund',
            319 => '.gift',
            320 => '.gold',
            321 => '.golf',
            322 => '.guru',
            323 => '.hair',
            324 => '.haus',
            325 => '.help',
            326 => '.host',
            327 => '.immo',
            328 => '.info',
            329 => '.kiwi',
            330 => '.land',
            331 => '.lgbt',
            332 => '.life',
            333 => '.limo',
            334 => '.link',
            335 => '.live',
            336 => '.loan',
            337 => '.love',
            338 => '.luxe',
            339 => '.menu',
            340 => '.mobi',
            341 => '.moda',
            342 => '.name',
            343 => '.news',
            344 => '.page',
            345 => '.pics',
            346 => '.pink',
            347 => '.plus',
            348 => '.porn',
            349 => '.qpon',
            350 => '.rent',
            351 => '.rest',
            352 => '.sale',
            353 => '.sarl',
            354 => '.scot',
            355 => '.shop',
            356 => '.show',
            357 => '.site',
            358 => '.skin',
            359 => '.surf',
            360 => '.taxi',
            361 => '.team',
            362 => '.tech',
            363 => '.tips',
            364 => '.town',
            365 => '.toys',
            366 => '.tube',
            367 => '.vote',
            368 => '.wang',
            369 => '.wien',
            370 => '.wiki',
            371 => '.wine',
            372 => '.work',
            373 => '.yoga',
            374 => '.zone',
            375 => '.app',
            376 => '.art',
            377 => '.bar',
            378 => '.bet',
            379 => '.bid',
            380 => '.bio',
            381 => '.biz',
            382 => '.cab',
            383 => '.cam',
            384 => '.com',
            385 => '.day',
            386 => '.dev',
            387 => '.dog',
            388 => '.eco',
            389 => '.fan',
            390 => '.fit',
            391 => '.fun',
            392 => '.fyi',
            393 => '.gay',
            394 => '.how',
            395 => '.ink',
            396 => '.kim',
            397 => '.lat',
            398 => '.lol',
            399 => '.ltd',
            400 => '.mba',
            401 => '.men',
            402 => '.moe',
            403 => '.mom',
            404 => '.net',
            405 => '.ngo',
            406 => '.nyc',
            407 => '.one',
            408 => '.ong',
            409 => '.onl',
            410 => '.org',
            411 => '.pet',
            412 => '.pro',
            413 => '.pub',
            414 => '.red',
            415 => '.rip',
            416 => '.run',
            417 => '.ski',
            418 => '.soy',
            419 => '.tax',
            420 => '.tel',
            421 => '.top',
            422 => '.uno',
            423 => '.vet',
            424 => '.vin',
            425 => '.vip',
            426 => '.win',
            427 => '.wtf',
            428 => '.xyz',
            429 => '.ac',
            430 => '.ae',
            431 => '.ag',
            432 => '.ai',
            433 => '.am',
            434 => '.as',
            435 => '.at',
            436 => '.au',
            437 => '.be',
            438 => '.bz',
            439 => '.ca',
            440 => '.cc',
            441 => '.ch',
            442 => '.cl',
            443 => '.cm',
            444 => '.co',
            445 => '.cx',
            446 => '.cz',
            447 => '.de',
            448 => '.dk',
            449 => '.ec',
            450 => '.es',
            451 => '.eu',
            452 => '.fi',
            453 => '.fm',
            454 => '.fr',
            455 => '.gd',
            456 => '.gg',
            457 => '.gl',
            458 => '.gr',
            459 => '.gs',
            460 => '.gy',
            461 => '.hn',
            462 => '.ht',
            463 => '.id',
            464 => '.im',
            465 => '.in',
            466 => '.io',
            467 => '.is',
            468 => '.it',
            469 => '.je',
            470 => '.jp',
            471 => '.la',
            472 => '.lc',
            473 => '.li',
            474 => '.lt',
            475 => '.lu',
            476 => '.lv',
            477 => '.me',
            478 => '.mn',
            479 => '.ms',
            480 => '.mu',
            481 => '.mx',
            482 => '.nl',
            483 => '.nu',
            484 => '.nz',
            485 => '.pe',
            486 => '.ph',
            487 => '.pl',
            488 => '.pm',
            489 => '.pt',
            490 => '.pw',
            491 => '.qa',
            492 => '.re',
            493 => '.sc',
            494 => '.se',
            495 => '.sg',
            496 => '.sh',
            497 => '.sx',
            498 => '.tc',
            499 => '.tf',
            500 => '.tk',
            501 => '.tl',
            502 => '.to',
            503 => '.tv',
            504 => '.tw',
            505 => '.uk',
            506 => '.us',
            507 => '.vc',
            508 => '.vg',
            509 => '.wf',
            510 => '.ws',
            511 => '.yt',
        ];
    }
}